# SPDX-FileCopyrightText: 2025 Supabase <support@supabase.io>
# SPDX-FileCopyrightText: 2025 Łukasz Niemier <~@hauleth.dev>
#
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: EUPL-1.2

name: Elixir tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  MIX_ENV: test

jobs:
  deps:
    name: Fetch deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get --check-locked

  format:
    name: Formatting checks
    runs-on: ubuntu-latest
    needs: [deps]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Run format check
        run: mix format --check-formatted

  credo:
    name: Code style
    runs-on: ubuntu-latest
    needs: [deps]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Compile deps
        run: mix deps.compile
      - name: Credo checks
        run: mix credo --strict --all --mute-exit-status --format=sarif > results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: results.sarif
          category: credo

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [deps]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Postgres
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: ./docker-compose.db.yml
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Cache native
        uses: actions/cache@v4
        with:
          path: |
            _build/${{ env.MIX_ENV }}/lib/supavisor/native
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-native-${{ hashFiles(format('{0}{1}', github.workspace, '/native/**/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-native-
      - name: Compile deps
        run: mix deps.compile
      - name: Compile
        run: mix compile
      - name: Start epmd
        run: epmd -daemon
      - name: Run tests
        run: mix coveralls.json
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: main
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: [deps]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Postgres
        uses: hoverkraft-tech/compose-action@v2.2.0
        with:
          compose-file: ./docker-compose.db.yml
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache-dependency-path: 'test/integration/js/'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Cache native
        uses: actions/cache@v4
        with:
          path: |
            _build/${{ env.MIX_ENV }}/lib/supavisor/native
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-native-${{ hashFiles(format('{0}{1}', github.workspace, '/native/**/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-native-
      - name: Compile deps
        run: mix deps.compile
      - name: Compile
        run: mix compile
      - name: Start epmd
        run: epmd -daemon
      - name: Install Node dependencies
        run: 'cd test/integration/js/; npm install'
      - name: Run tests
        run: mix coveralls.json --only integration --trace
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: integration
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  dialyzer:
    name: Dialyze
    runs-on: ubuntu-latest
    needs: [deps]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: '27.2.1'
          elixir-version: '1.18.2'
      - name: Cache Mix
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Cache native
        uses: actions/cache@v4
        with:
          path: |
            _build/${{ env.MIX_ENV }}/lib/supavisor/native
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-build-native-${{ hashFiles(format('{0}{1}', github.workspace, '/native/**/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-native-
      - name: Compile deps
        run: mix deps.compile
      - name: Compile
        run: mix compile
      - name: Retrieve PLT Cache
        uses: actions/cache@v4
        id: plt-cache
        with:
          path: _build/${{ env.MIX_ENV }}/*.plt
          key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plts-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plts-

      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer.build
      - name: Run dialyzer
        run: mix dialyzer
